import 'dart:ui';

class ColorApp {
  ColorApp._();
  static const Color btn_orange = Color(0xFFF18A6D);
  static const Color btn_pink = Color(0xFFEC9BAD);
  static const Color btn_maroon = Color(0xFF9F2241);
  static const Color btn_grey = Color(0xFFA8A8A8);
  static const Color arrow_white = Color(0xFFFFFAF6);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color black_font = Color(0xFF231F20);
  static const Color black_font_underline = Color(0xFF0F0F0E);
  static const Color black_arrow_back = Color(0xFF1A1919);
  static const Color grey_font = Color(0xFF757583);
  static const Color text_input_bg = Color(0xFFFAEDE3);
  static const Color grey_divider = Color(0xFFA8A8A8);
  static const Color txt_white = Color(0xFFFFFDFB);
  static const Color broken_white = Color(0x4DFFFFFF);
  static const Color btn_switch_green = Color(0xFF64C366);
  static const Color bottom_nav_color = Color(0xFFFAEDE3);
  static const Color homepage_name_color = Color(0xFF321F0E);
  static const Color black_greeting_color = Color(0xFF292929);
  static const Color ic_notif_color = Color(0xFF111318);
  static const Color black_article_title = Color(0xFF222222);
  static const Color purple_article_dummy = Color(0xFF9897F4);
  static const Color black_font_30 = Color(0x4D000000);
  static const Color blue_container = Color(0xFF365888);
  static const Color black_view_all = Color(0xFF0A0A0B);
  static const Color black_font_40 = Color(0x660F0F0E);
  static const Color black_font_50 = Color(0x800F0F0E);
  static const Color white_font = Color(0xFFF8F5EE);
  static const Color grey_card_font = Color(0xFFFCFBF7);
  static const Color dash_color = Color(0xFFB7B6B4);
  static const Color grey_container = Color(0xFFD9D9D9);
  static const Color container_pink = Color(0xFFFFE1DC);
  static const Color grey_tab_title = Color(0xFF646464);
  static const Color yellow_icon = Color(0xFFFFCA43);
  static const Color red_error = Color(0xFFE53B3B);
}